### PR TITLE
Update documentation with example for custom serialization

### PR DESCRIPTION
**Pull request by chrismostert**
## 📒 Description

Adds a small snippet to the documentation on how to register a custom serialization function for a specific data type. This approach can be used to resolve issues like https://github.com/tefra/xsdata/issues/917
(Apologies for the messy PR #976, please consider this PR)

## 🔗 What I've Done

Since no changes in the code were required, the documentation has been updated with a small code snippet.

## 💬 Comments

Please check if the snippet is informative enough and in the correct place in the documentation

## 🛫 Checklist

- [x] Updated docs
- [x] Added unit-tests (not needed)
- [x] [Sample tests](https://github.com/tefra/xsdata-samples) pass
- [x] [W3C tests](https://github.com/tefra/xsdata-w3c-tests) pass

### CODE REVIEW

**Comment by tefra** [comment]
I am wondering, if this example is too similar to [this ](https://xsdata.readthedocs.io/en/latest/models/types/#user-types) one, maybe we should expand that one, what do you think?

**Comment by chrismostert** [comment]
> I am wondering, if this example is too similar to [this ](https://xsdata.readthedocs.io/en/latest/models/types/#user-types) one, maybe we should expand that one, what do you think?

I do agree that the general setup is quite similar! I feel like that example might be trying to explain too much if we also override some standard type's `serialize` function. I could move it as an additional snippet below that one with a heading of **Overriding standard type conversion**, what do you think?

**Comment by tefra** [comment]
> > I am wondering, if this example is too similar to [this ](https://xsdata.readthedocs.io/en/latest/models/types/#user-types) one, maybe we should expand that one, what do you think?
> 
> I do agree that the general setup is quite similar! I feel like that example might be trying to explain too much if we also override some standard type's `serialize` function. I could move it as an additional snippet below that one with a heading of **Overriding standard type conversion**?

Yes, let's do that thank you!

**Review by tefra — APPROVED** [review]
Thank you @chrismostert

**Pull request merged**
